AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda for Transcribe with SQS Event Triggers

Parameters:
  LambdasCodeS3BucketName:
    Type: String
    Description: Name of the pre created bucket that stores lambda code zip file
  EnvironmentName:
    Type: String
    Description: Name of the the environment of the lambda (e.g. development, production)
  DynamoDBTableName:
    Type: String
    Description: Name for the DynamoDB Table
  DynamoDBTableArn:
    Type: String
    Description: Arn of the DynamoDB Table
  CustomAnalysisQueueUrl:
    Type: String
    Description: URL of the Custom Analysis SQS Queue
  CustomAnalysisQueueArn:
    Type: String
    Description: Arn of the Custom Analysis SQS Queue
  StackName:
    Type: String
    Description: Name of the parent stack

Resources:
  # Lambda Execution Role for Transcribe Lambda
  TranscribeLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TranscribeLambdaPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - transcribe:StartTranscriptionJob
                  - transcribe:GetTranscriptionJob
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
        - PolicyName: DynamoDBCRUDPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:Scan
                  - dynamodb:DescribeTable
                Resource:
                  - !Ref DynamoDBTableArn # Main table ARN
                  - !Sub ${DynamoDBTableArn}/* # Includes all GSIs of the table
        - PolicyName: SendSQSMessage
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:sendmessage
                Resource:
                  - !Ref CustomAnalysisQueueArn

  # Transcribe Lambda Function
  TranscribeLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: TranscribeVideoLambda
      Handler: index.handler
      Timeout: 900
      Role: !GetAtt TranscribeLambdaRole.Arn
      Code:
        S3Bucket: !Ref LambdasCodeS3BucketName
        S3Key: !Sub ${EnvironmentName}/transcribe-lambda.zip
      Runtime: nodejs20.x
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTableName
          SQS_QUEUE_URL: !Ref CustomAnalysisQueueUrl
      LoggingConfig:
        LogGroup: !Ref TranscribeLambdaCloudWatchLogsGroup
    DeletionPolicy: Delete

  TranscribeLambdaCloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /lambda/transcribe
      RetentionInDays: 14
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain

Outputs:
  TranscribeLambdaArn:
    Description: ARN of the Transcribe Lambda function
    Value: !GetAtt TranscribeLambda.Arn
    Export:
      Name: !Sub ${StackName}-TranscribeLambdaArn
