name: video-llava
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - pip
  - pip:
    - transformers
    - av
    - numpy
    - requests