AWSTemplateFormatVersion: '2010-09-09'
Description: 'Application Load Balancer for API Cluster'

Parameters:
  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID
  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Public Subnet 1 ID
  PublicSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Public Subnet 2 ID
  DomainName:
    Type: String
    Description: Domain name for the ALB
  HostedZoneId:
    Type: String
    Description: The ID of the hosted zone in Route 53
  StackName:
    Type: String
    Description: Name of the parent stack

Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref ALB
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref ACMCertificate

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: /health
      Name: ALBTargetGroup
      Port: 4000
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VPCId

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ALB
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  ACMCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId

  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt ALB.DNSName
        HostedZoneId: !GetAtt ALB.CanonicalHostedZoneID

Outputs:
  ALBDNSName:
    Description: DNS name of the Application Load Balancer
    Value: !GetAtt ALB.DNSName
    Export:
      Name: !Sub ${StackName}-ALBDNS
  ALBTargetGroupArn:
    Description: Target Group of the Application Load Balancer
    Value: !GetAtt ALBTargetGroup.TargetGroupArn
    Export:
      Name: !Sub ${StackName}-ALBTargetGroup
  ALBSecurityGroupId:
    Description: Security Group of the Application Load Balancer
    Value: !GetAtt ALBSecurityGroup.GroupId
    Export:
      Name: !Sub ${StackName}-ALBTargetGroup
