AWSTemplateFormatVersion: '2010-09-09'
Description: SNS Topic and SQS Queues for Video Processing Pipeline

Parameters:
  StackName:
    Type: String
    Description: Name of the parent stack

Resources:
  # SNS Topic
  VideoProcessingTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: VideoProcessingTopic

  # SQS Queue for Custom Analysis
  CustomAnalysisQueue:
    Type: AWS::SQS::Queue
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      QueueName: CustomAnalysisQueue
      VisibilityTimeout: 900 # 15 minutes
      ReceiveMessageWaitTimeSeconds: 20 # Long polling
      MessageRetentionPeriod: 604800 # 1 week

  # SQS Queue for Amazon Transcribe
  TranscribeQueue:
    Type: AWS::SQS::Queue
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      QueueName: TranscribeQueue
      VisibilityTimeout: 900 # 15 minutes
      MessageRetentionPeriod: 604800 # 1 week

  # SQS Queue for Amazon Rekognition
  RekognitionQueue:
    Type: AWS::SQS::Queue
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      QueueName: RekognitionQueue
      VisibilityTimeout: 900 # 15 minutes
      MessageRetentionPeriod: 604800 # 1 week

  # SNS Subscriptions
  SNSCustomAnalysisSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref VideoProcessingTopic
      Endpoint: !GetAtt CustomAnalysisQueue.Arn
      Protocol: sqs
      RawMessageDelivery: true

  SNSTranscribeSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref VideoProcessingTopic
      Endpoint: !GetAtt TranscribeQueue.Arn
      Protocol: sqs
      RawMessageDelivery: true

  SNSRekognitionSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref VideoProcessingTopic
      Endpoint: !GetAtt RekognitionQueue.Arn
      Protocol: sqs
      RawMessageDelivery: true

  # SQS Queue Policy to allow SNS to send messages to the queues
  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref CustomAnalysisQueue
        - !Ref TranscribeQueue
        - !Ref RekognitionQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: 'sns.amazonaws.com'
            Action: 'SQS:SendMessage'
            Resource:
              - !GetAtt CustomAnalysisQueue.Arn
              - !GetAtt TranscribeQueue.Arn
              - !GetAtt RekognitionQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref VideoProcessingTopic

Outputs:
  VideoProcessingTopicArn:
    Description: ARN of the SNS topic
    Value: !GetAtt VideoProcessingTopic.TopicArn
    Export:
      Name: !Sub ${StackName}-VideoProcessingTopicArn

  CustomAnalysisQueueUrl:
    Description: URL of the Custom Analysis SQS Queue
    Value: !GetAtt CustomAnalysisQueue.QueueUrl
    Export:
      Name: !Sub ${StackName}-CustomAnalysisQueueUrl

  CustomAnalysisQueueArn:
    Description: Arn of the Custom Analysis SQS Queue
    Value: !GetAtt CustomAnalysisQueue.Arn
    Export:
      Name: !Sub ${StackName}-CustomAnalysisQueueArn

  TranscribeQueueUrl:
    Description: URL of the Amazon Transcribe SQS Queue
    Value: !GetAtt TranscribeQueue.QueueUrl
    Export:
      Name: !Sub ${StackName}-TranscribeQueueUrl

  TranscribeQueueArn:
    Description: Arn of the Transcribe SQS Queue
    Value: !GetAtt TranscribeQueue.Arn
    Export:
      Name: !Sub ${StackName}-TranscribeQueueArn

  RekognitionQueueUrl:
    Description: URL of the Amazon Rekognition SQS Queue
    Value: !GetAtt RekognitionQueue.QueueUrl
    Export:
      Name: !Sub ${StackName}-RekognitionQueueUrl

  RekognitionQueueArn:
    Description: Arn of the Amazon Rekognition SQS Queue
    Value: !GetAtt RekognitionQueue.Arn
    Export:
      Name: !Sub ${StackName}-RekognitionQueueArn
