AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket to store video uploads (and trigger lambdas)

Parameters:
  AccountId:
    Type: String
    Description: AWS account ID (needed for lambda permission)
  VideoStorageS3BucketName:
    Type: String
    Description: Name of the S3 bucket that will store uploaded videos
  TranscribeLambdaArn:
    Type: String
    Description: ARN of the Transcribe Lambda function
  RekognitionLambdaArn:
    Type: String
    Description: ARN of the Rekognition Lambda function
  StackName:
    Type: String
    Description: Name of the parent stack

Resources:
  VideoStorageS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref VideoStorageS3BucketName
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  # EventBridge Rule
  S3UploadRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: 'Rule to capture S3 upload events and trigger Lambda functions'
      State: 'ENABLED'
      EventPattern:
        source:
          - 'aws.s3'
        detail-type:
          - 'Object Created'
        detail:
          bucket:
            name:
              - !Ref VideoStorageS3BucketName
      Targets:
        - Arn: !Ref TranscribeLambdaArn
          Id: 'TranscribeLambda'
        - Arn: !Ref RekognitionLambdaArn
          Id: 'RekognitionLambda'

    # Grant permission for S3 to invoke the Transcribe Lambda
  TranscribeLambdaPermissionForS3:
    Type: AWS::Lambda::Permission
    Properties:
      SourceAccount: !Ref AccountId
      Action: lambda:InvokeFunction
      FunctionName: !Ref TranscribeLambdaArn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt S3UploadRule.Arn

    # Grant permission for S3 to invoke the Rekognition Lambda
  RekognitionLambdaPermissionForS3:
    Type: AWS::Lambda::Permission
    Properties:
      SourceAccount: !Ref AccountId
      Action: lambda:InvokeFunction
      FunctionName: !Ref RekognitionLambdaArn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt S3UploadRule.Arn

Outputs:
  VideoStorageS3BucketArn:
    Description: ARN of the video storage s3 bucket
    Value: !GetAtt VideoStorageS3Bucket.Arn
    Export:
      Name: !Sub ${StackName}-VideoStorageS3BucketArn
