AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda for video thumbnail creation on video upload

Parameters:
  LambdasCodeS3BucketName:
    Type: String
    Description: Name of the pre created bucket that stores lambda code zip file
  EnvironmentName:
    Type: String
    Description: Name of the the environment of the lambda (e.g. development, production)
  DynamoDBTableName:
    Type: String
    Description: Name for the DynamoDB Table
  DynamoDBTableArn:
    Type: String
    Description: Arn of the DynamoDB Table
  StackName:
    Type: String
    Description: Name of the parent stack

Resources:
  FFMPEGLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs10.x
        - python3.6
        - ruby2.5
        - java8
        - go1.x
      Content:
        S3Bucket: awsserverlessrepo-changesets-18ssd5swmy82n
        S3Key: 340752834213/arn:aws:serverlessrepo:us-east-1:145266761615:applications-ffmpeg-lambda-layer-versions-1.0.0/1fc0da99-81d9-49d0-9972-8db310c3fc72
      Description: FFMPEG for AWS Lambda
      LayerName: ffmpeg
      LicenseInfo: GPL-2.0-or-later

  # Lambda Execution Role for Thumbnail Lambda
  ThumbnailLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ThumbnailLambdaPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
        - PolicyName: DynamoDBCRUDPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:Scan
                  - dynamodb:DescribeTable
                Resource:
                  - !Ref DynamoDBTableArn # Main table ARN
                  - !Sub ${DynamoDBTableArn}/* # Includes all GSIs of the table

  # Thumbnail Lambda Function
  ThumbnailLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ThumbnailVideoLambda
      Handler: index.handler
      Timeout: 900
      Role: !GetAtt ThumbnailLambdaRole.Arn
      Code:
        S3Bucket: !Ref LambdasCodeS3BucketName
        S3Key: !Sub ${EnvironmentName}/thumbnail-lambda.zip
      Runtime: nodejs20.x
      Layers:
        - !GetAtt FFMPEGLayer.LayerVersionArn
      Environment:
        Variables:
          FFMPEG_PATH: /opt/ffmpeg/ffmpeg
          FFPROBE_PATH: /opt/ffmpeg/ffprobe
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTableName
      LoggingConfig:
        LogGroup: !Ref ThumbnailLambdaCloudWatchLogsGroup
    DeletionPolicy: Delete

  ThumbnailLambdaCloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /lambda/thumbnail
      RetentionInDays: 14
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain

Outputs:
  ThumbnailLambdaArn:
    Description: ARN of the Thumbnail Lambda function
    Value: !GetAtt ThumbnailLambda.Arn
    Export:
      Name: !Sub ${StackName}-ThumbnailLambdaArn
