name: API Deployment
on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**' # Only run when files in the api app directory change

permissions: # necessary for the GitHub OIDC provider to authenticate with AWS
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository code
      - uses: actions/checkout@v4

      # Sets up Node.js environment
      # - name: Set up Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'

      # Installs project dependencies
      # - name: Install dependencies
      #   run: npm ci # Uses clean install to ensure consistent builds (npm i alternative)

      # Builds the api project
      # - name: Build api
      #   run: npm run build -- --filter=api # Uses Turborepo to build only the api

      # Configures AWS credentials using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActionsDeployment

      # Logs into Amazon ECR (Elastic Container Registry) to allow pushing Docker images
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Builds Docker image, tags it with the Git commit SHA, and pushes it to ECR
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.API_ECR_REPOSITORY_NAME }}
          SHA: ${{ github.sha }}
        run: |
          # Extract first 7 characters of the SHA
          SHORT_SHA=${SHA:0:7}

          # Build the Docker image
          docker build \
           -f ./apps/api/Dockerfile
           -t $ECR_REGISTRY/$ECR_REPOSITORY:$SHORT_SHA \
           -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .

          # Push the Docker image
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$SHORT_SHA
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # ECS service rolling update with the new image
      - name: ECS service update
        env:
          CLUSTER_NAME: ${{ secrets.API_CLUSTER_NAME }}
          SERVICE_NAME: ${{ secrets.API_SERVICE_NAME }}
        run: |
          # Update ECS service with latest image
          aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment \
          --task-definition $(aws ecs describe-task-definition --task-definition $(aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME --query "services[0].taskDefinition" --output text) --query "taskDefinition.taskDefinitionArn" --output text)
