name: Backend Deployment
on:
  push:
    branches:
      - main
    paths:
      - 'apps/backend/**' # Only run when files in the backend app directory change

permissions: # necessary for the GitHub OIDC provider to authenticate with AWS
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository code
      - uses: actions/checkout@v4

      # Sets up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Installs project dependencies
      - name: Install dependencies
        run: npm ci # Uses clean install to ensure consistent builds (npm i alternative)

      # Builds the backend project
      - name: Build backend
        run: npm run build --filter=./apps/backend # Uses Turborepo to build only the backend

      # Configures AWS credentials using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-south-2
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActionsDeployment

      # Logs into Amazon ECR (Elastic Container Registry) to allow pushing Docker images
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Builds Docker image, tags it with the Git commit SHA, and pushes it to ECR
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
          SHA: ${{ github.sha }}
        run: |
          # Extract first 7 characters of the SHA
          SHORT_SHA=${SHA:0:7}

          # Build the Docker image
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$SHORT_SHA -t $ECR_REGISTRY/$ECR_REPOSITORY:latest apps/backend

          # Push the Docker image
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$SHORT_SHA
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # Temporarily scale up the number of EC2 instances to perform the rolling update
      # of the ECS service with the new image
      - name: Dynamic scaling and ECS service update
        env:
          CLUSTER_NAME: ${{ secrets.ECS_CLUSTER_NAME }}
          SERVICE_NAME: ${{ secrets.ECS_SERVICE_NAME }}
        run: |
          # Update ECS service with latest image
          aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment \
          --task-definition $(aws ecs describe-task-definition --task-definition $(aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME --query "services[0].taskDefinition" --output text) --query "taskDefinition.taskDefinitionArn" --output text)

      # # Temporarily scale up the number of EC2 instances to perform the rolling update
      # # of the ECS service with the new image
      # - name: Dynamic scaling and ECS service update
      #   env:
      #   run: |
      #     # Get current EC2 instance count and Auto Scaling group settings
      #     current_instances=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names $ASG_NAME --query "AutoScalingGroups[0].Instances[].InstanceId" --output text | wc -w)
      #     current_max=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names $ASG_NAME --query "AutoScalingGroups[0].MaxSize" --output text)

      #     # Calculate new capacity (double capacity temporarily to ensure replacement tasks can be placed)
      #     new_capacity=$((current_instances * 2))

      #     # Calculate new max capacity (ensure it's at least the new_capacity)
      #     new_max=$((new_capacity > current_max ? new_capacity : current_max))

      #     echo "Current instances: $current_instances, current max: $current_max"
      #     echo "Scaling to: $new_capacity, new max: $new_max"

      #     # Update Auto Scaling group with new max capacity and desired capacity
      #     aws autoscaling update-auto-scaling-group --auto-scaling-group-name $ASG_NAME --max-size $new_max --desired-capacity $new_capacity

      #     # Wait for new instances to be in service
      #     while true; do
      #       in_service=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names $ASG_NAME --query "AutoScalingGroups[0].Instances[?LifecycleState=='InService' && HealthStatus=='Healthy'].InstanceId" --output text | wc -w)
      #       if [ "$in_service" -ge "$new_capacity" ]; then
      #         break
      #       fi
      #       echo "Waiting for instances to be in service: $in_service/$new_capacity"
      #       sleep 30
      #     done

      #     # Update ECS service with new image
      #     aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment \
      #     --task-definition $(aws ecs describe-task-definition --task-definition $(aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME --query "services[0].taskDefinition" --output text) --query "taskDefinition.taskDefinitionArn" --output text)

      #     # Wait for the new deployment to be stable
      #     aws ecs wait services-stable --cluster $CLUSTER_NAME --services $SERVICE_NAME

      #     # Scale down to original capacity and reset max size
      #     aws autoscaling update-auto-scaling-group --auto-scaling-group-name $ASG_NAME --max-size $current_max --desired-capacity $current_instances
