name: Stack Upload
on:
  push:
    branches:
      - main
    paths:
      # Only run when files in infrastructure directories change
      - 'infrastructure/**.yml'
      - 'apps/api/infrastructure/**.yml'
      - 'apps/analysis-model/infrastructure/**.yml'
      - 'apps/transcribe-lambda/infrastructure/**.yml'
      - 'apps/rekognition-lambda/infrastructure/**.yml'
      - 'apps/thumbnail-lambda/infrastructure/**.yml'

permissions: # necessary for the GitHub OIDC provider to authenticate with AWS
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository code
      - uses: actions/checkout@v4

      # Configures AWS credentials using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActionsDeployment

      # Upload API CloudFormation templates to S3
      - name: Upload API CloudFormation templates to S3
        env:
          S3_BUCKET: ${{ secrets.STACK_TEMPLATES_S3_BUCKET_NAME }}
        run: |
          # Sync .yml files to /api path
          aws s3 sync apps/api/infrastructure s3://$S3_BUCKET/api/ \
          --delete --exclude "*" --include "*.yml"

          # Sync .yml files to /analysis-model path
          aws s3 sync apps/analysis-model/infrastructure s3://$S3_BUCKET/analysis-model/ \
          --delete --exclude "*" --include "*.yml"

          # Sync .yml files to /transcribe-lambda path
          aws s3 sync apps/transcribe-lambda/infrastructure s3://$S3_BUCKET/transcribe-lambda/ \
          --delete --exclude "*" --include "*.yml"

          # Sync .yml files to /rekognition-lambda path
          aws s3 sync apps/rekognition-lambda/infrastructure s3://$S3_BUCKET/rekognition-lambda/ \
          --delete --exclude "*" --include "*.yml"

          # Sync .yml files to /rekognition-lambda path
          aws s3 sync apps/thumbnail-lambda/infrastructure s3://$S3_BUCKET/thumbnail-lambda/ \
          --delete --exclude "*" --include "*.yml"

          # Sync .yml files to /main path
          aws s3 sync infrastructure/stacks s3://$S3_BUCKET/main/ \
          --delete --exclude "*" --include "*.yml"
